### ISSUE TITLE
新版本更新

### ISSUE THREAD

**Issue by 986138497** [aidevjoe/ATAuthSDK#1]
大佬,新版本已经更新了, 可有时间更新下pod

**Comment by aidevjoe** [comment]
2.12.1.3 已是最新版，没有发现有更新

**Comment by 986138497** [comment]
不好意思, 安卓是新的, ios 还是 6 月份的
![image](https://user-images.githubusercontent.com/18497058/130019058-7df8ef0e-1892-48dc-af79-70185be3abf6.png)
